6.15: workaround: offer disabling bcachefs when building BDS/BMQ
Closes: #1126
Bug: #1120

diff --git a/linux-tkg-config/prepare b/linux-tkg-config/prepare
--- a/linux-tkg-config/prepare
+++ b/linux-tkg-config/prepare
@@ -1731,6 +1731,18 @@ fi
     yes "" | make LSMOD=$_modprobeddb_db_path localmodconfig ${llvm_opt}
   fi
 
+  if [[ "${_cpusched}" =~ ^(pds|bmq)$ && "$_kver" == 615 ]]; then
+    warning "PDS/BMQ is currently not compatible with bcachefs on kernel 6.15, disable bcachefs ?"
+    read -p "Y/[n]: " _disable_bcachefs
+
+    if [[ "$_disable_bcachefs" =~ ^(Y|y|Yes|yes)$ ]]; then
+      _disable BCACHEFS_FS
+    else
+      error "6.15 Kernel cannot be built with PDS/BMQ _and_ bcachefs, exiting"
+      exit 1
+    fi
+  fi
+
   if [ true = "$_config_fragments" ]; then
     local fragments=()
     mapfile -d '' -t fragments < <(find "$_where"/ -type f -name "*.myfrag" -print0 | sort -z)
