prepare: add _replace() function
it fails if the thing we're trying to replace doesn't exist

diff --git a/linux-tkg-config/prepare b/linux-tkg-config/prepare
--- a/linux-tkg-config/prepare
+++ b/linux-tkg-config/prepare
@@ -171,6 +171,21 @@ _vanilla_mode() {
   [[ "$_vanilla" =~ ^(Y|y|Yes|yes|true|1)$ ]];
 }
 
+_replace() {
+  local search="$1"
+  local replace="$2"
+  local file="$3"
+
+  local delim=$'\x01'
+
+  if ! grep -qF -- "$search" "$file"; then
+    error "Pattern '$search' not found in $file"
+    exit 1
+  fi
+
+  sed -i "s${delim}${search}${delim}${replace}${delim}g" "$file"
+}
+
 _prompt_from_array() {
   # Prompts from array, selects default index on empty user input
   # Set the _default_index variable to enable default index selection
