prepare: exit on failed patch application
otherwise there's a chance that a broken kernel successfully builds
and better fail earlier than later during compilation

Bug: #1226

diff --git a/linux-tkg-config/prepare b/linux-tkg-config/prepare
--- a/linux-tkg-config/prepare
+++ b/linux-tkg-config/prepare
@@ -743,7 +743,10 @@ _tkg_patcher() {
   if [ -e "$tkgpatch" ] && [[ $(wc -l <"$tkgpatch") -ge 7 ]]; then
     msg2 "$_msg"
     echo -e "### Applying ${tkgpatch##*/}... ###" >> "$_where"/logs/prepare.log.txt
-    patch -Np1 -i "$tkgpatch" >> "$_where"/logs/prepare.log.txt || error "An error was encountered applying patches. It was logged to the prepare.log.txt file."
+    if ! patch -Np1 -i "$tkgpatch" >> "$_where"/logs/prepare.log.txt; then
+      error "Patch application failed. Debug logs in prepare.log.txt file."
+      exit 1
+    fi
     echo -e "\n" >> "$_where"/logs/prepare.log.txt
   else
     msg2 "Skipping patch ${tkgpatch##*/}...\n         (unavailable for this kernel version)"
