Pipe patcher output to a prepare.log file

diff --git a/linux-tkg-config/prepare b/linux-tkg-config/prepare
--- a/linux-tkg-config/prepare
+++ b/linux-tkg-config/prepare
@@ -288,7 +288,9 @@ user_patcher() {
 
 _tkg_patcher() {
   if [ -e "$tkgpatch" ]; then
-    patch -Np1 -i "$tkgpatch"
+    echo -e "### Applying ${tkgpatch##*/}... ###" >> "$_where"/prepare.log
+    patch -Np1 -i "$tkgpatch" >> "$_where"/prepare.log || error "An error was encountered applying patches. It was logged to the prepare.log file."
+    echo -e "\n" >> "$_where"/prepare.log
   else
     msg2 "Patch either not found, not available for this kernel version or not needed. Skipping..."
   fi
@@ -304,6 +306,7 @@ _tkg_srcprep() {
     msg2 "Setting version..."
     scripts/setlocalversion --save-scmversion
     echo "-$pkgrel-tkg-${_cpusched}${_compiler_name}" > localversion.10-pkgrel
+    echo -e "Version tail set to \"-$pkgrel-tkg-${_cpusched}${_compiler_name}\"\n" > "$_where"/prepare.log
     echo "" > localversion.20-pkgname
 
     # add upstream patch
